// SRQ Wash — Site-wide constants and data
// Design: Florida Power — Slate Black + Pressure Blue + Safety Orange

export const SITE = {
  name: "SRQ Wash",
  tagline: "Lakewood Ranch's Premier Pressure Washing Company",
  description:
    "Professional pressure washing, soft wash roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing in Lakewood Ranch, Sarasota, Bradenton, and Venice, FL.",
  address: "9040 Town Center Pkwy #102, Lakewood Ranch FL 34202",
  email: "srqwash@gmail.com",
  // Display phone (from site)
  phoneDisplay: "(941) 299-6338",
  // Call button phone (hidden from display, used for tel: links only)
  phoneCall: "9412292355",
  rating: "4.90",
  reviewCount: "48",
  hours: [
    { day: "Monday", hours: "7am – 7pm" },
    { day: "Tuesday", hours: "7am – 7pm" },
    { day: "Wednesday", hours: "7am – 7pm" },
    { day: "Thursday", hours: "7am – 7pm" },
    { day: "Friday", hours: "7am – 7pm" },
    { day: "Saturday", hours: "7am – 7pm" },
    { day: "Sunday", hours: "Closed" },
  ],
  social: {
    facebook: "https://www.facebook.com/Srqwash",
    instagram: "https://www.instagram.com/srqwash/",
    youtube: "https://www.youtube.com/@srqwash",
  },
  partnerSite: {
    name: "TomThePoolGuy.com",
    url: "https://tomthepoolguy.com",
  },
};

export const SERVICES = [
  {
    id: "roof-cleaning",
    slug: "/roof-cleaning",
    title: "Roof Cleaning",
    shortTitle: "Roof Cleaning",
    subtitle: "Safe Soft Wash Roof Cleaning in Lakewood Ranch & Sarasota",
    description:
      "Your roof requires specialized care to maintain its appearance and functionality. Our professional roof cleaning service uses safe soft washing methods to eliminate algae, moss, and organic growth without the risk of damage associated with high-pressure washing. We exclusively use techniques recommended by major roofing manufacturers to protect your investment.",
    longDescription: `Florida's humid climate creates the perfect environment for algae, mold, and lichen to colonize your roof. Those dark streaks you see are not just cosmetic — they are living organisms that shorten the lifespan of your roofing materials. Our professional soft wash roof cleaning service uses low-pressure application combined with biodegradable cleaning solutions to kill organic growth at the cellular level, providing results that last 2–4 times longer than pressure washing alone.

We follow ARMA (Asphalt Roofing Manufacturers Association) guidelines and use only manufacturer-approved cleaning methods. This means your roof warranty remains intact and your investment is protected. Our process is safe for all roof types including tile, shingle, metal, and flat roofs.`,
    benefits: [
      "Extends roof lifespan by removing damaging organic growth",
      "Manufacturer-approved soft wash methods — warranty safe",
      "Results last 2–4x longer than pressure washing",
      "Eliminates algae, mold, lichen, and moss at the root",
      "Protects your home's curb appeal and resale value",
    ],
    image: "/manus-storage/job-roof-cleaning-1_3cdf5e49.webp",
    metaTitle:
      "Roof Cleaning Lakewood Ranch & Sarasota | Safe Soft Wash | SRQ Wash",
    metaDescription:
      "Professional soft wash roof cleaning in Lakewood Ranch, Sarasota, and Bradenton. Safe, manufacturer-approved methods that eliminate algae, mold, and streaks without damage. Free quotes.",
  },
  {
    id: "house-washing",
    slug: "/house-washing",
    title: "Exterior House Washing",
    shortTitle: "House Washing",
    subtitle: "Professional Exterior House Washing in Lakewood Ranch",
    description:
      "Our professional house washing service in Lakewood Ranch uses a combination of soft washing and pressure washing techniques to safely and effectively clean all types of exterior surfaces. We begin every project with a thorough inspection to determine the most appropriate cleaning method for your specific siding, stucco, or trim materials.",
    longDescription: `Your home's exterior is constantly exposed to Florida's harsh elements — UV radiation, humidity, salt air, and biological growth. Over time, this leads to unsightly staining, mold growth, and surface degradation that can affect your property value and HOA compliance. Our professional exterior house washing service restores your home's original beauty and protects your investment.

We use a tailored approach for every home. Stucco and painted surfaces receive our gentle soft wash treatment, while harder surfaces like brick and concrete may benefit from controlled pressure washing. Our eco-friendly cleaning solutions are safe for your landscaping, family, and pets.`,
    benefits: [
      "Removes mold, mildew, algae, and environmental staining",
      "Safe for all exterior surfaces — stucco, siding, brick, wood",
      "Eco-friendly solutions safe for plants, pets, and family",
      "Improves curb appeal and maintains property value",
      "Helps maintain HOA compliance",
    ],
    image: "/manus-storage/job-roof-cleaning-2_c66b2d1d.webp",
    metaTitle:
      "House Washing Lakewood Ranch & Sarasota | Exterior Cleaning | SRQ Wash",
    metaDescription:
      "Professional exterior house washing in Lakewood Ranch, Sarasota, and Bradenton. Safe soft wash and pressure wash for stucco, siding, and brick. Free quotes.",
  },
  {
    id: "driveway-cleaning",
    slug: "/driveway-cleaning",
    title: "Driveway & Concrete Cleaning",
    shortTitle: "Driveway Cleaning",
    subtitle: "Professional Driveway & Concrete Cleaning in Lakewood Ranch",
    description:
      "Your driveway and concrete surfaces are among the first things visitors notice when they arrive at your Lakewood Ranch property. Our professional driveway cleaning and concrete restoration service removes oil stains, tire marks, organic growth, and general discoloration using professional-grade surface cleaners that provide even, consistent results across large areas.",
    longDescription: `Concrete driveways, walkways, and pool decks are porous surfaces that absorb oil, grease, rust, and organic matter over time. Standard garden hoses and consumer pressure washers simply cannot generate the pressure or apply the right cleaning chemistry to restore concrete to its original appearance. Our professional surface cleaning equipment uses rotating nozzles that clean evenly without leaving streaks or lines.

We pre-treat oil stains and heavy organic growth with specialized degreasers and biocides before applying high-pressure cleaning. Post-treatment with a surface sealer is available to protect your investment and make future cleaning easier.`,
    benefits: [
      "Removes oil stains, tire marks, rust, and organic growth",
      "Professional surface cleaners for streak-free, even results",
      "Pre-treatment for stubborn stains",
      "Optional sealing to protect and extend clean appearance",
      "Improves safety by removing slippery algae and mold",
    ],
    image: "/manus-storage/job-roof-before-after-1_68f4e192.webp",
    metaTitle:
      "Driveway Cleaning Lakewood Ranch & Sarasota | Concrete Cleaning | SRQ Wash",
    metaDescription:
      "Professional driveway and concrete cleaning in Lakewood Ranch, Sarasota, and Bradenton. Remove oil stains, tire marks, and organic growth. Free quotes.",
  },
  {
    id: "pool-cage-cleaning",
    slug: "/pool-cage-cleaning",
    title: "Pool Cage & Lanai Cleaning",
    shortTitle: "Pool Cage Cleaning",
    subtitle: "Pool Cage, Lanai & Patio Cleaning in Lakewood Ranch",
    description:
      "Pool areas present unique cleaning challenges that require specialized attention. Our pool area cleaning service addresses all aspects of pool deck and surrounding area maintenance, removing algae and organic growth while restoring proper slip resistance for safety.",
    longDescription: `Florida's pool cages and screen enclosures are constantly exposed to humidity, rain, pollen, and organic growth. Algae, mold, and oxidation build up on aluminum frames and screen panels, reducing visibility and creating an unsightly appearance. Our specialized pool cage cleaning service uses the right pressure and chemistry to clean screens without tearing them and restore aluminum frames to their original luster.

We also clean pool decks, lanai pavers, and surrounding concrete areas. Our process removes algae and mold that create dangerous slip hazards, restoring safe, clean surfaces for your family to enjoy.`,
    benefits: [
      "Cleans aluminum frames and screen panels safely",
      "Removes algae, mold, and oxidation from enclosures",
      "Restores slip resistance to pool decks and lanais",
      "Improves visibility through clean screen panels",
      "Extends the life of your screen enclosure",
    ],
    image: "/manus-storage/job-roof-after-1_90c9f27b.webp",
    metaTitle:
      "Pool Cage Cleaning Lakewood Ranch & Sarasota | Lanai Cleaning | SRQ Wash",
    metaDescription:
      "Professional pool cage, lanai, and patio cleaning in Lakewood Ranch, Sarasota, and Bradenton. Safe screen cleaning, algae removal, and deck restoration. Free quotes.",
  },
  {
    id: "paver-sealing",
    slug: "/paver-sealing",
    title: "Paver Sealing",
    shortTitle: "Paver Sealing",
    subtitle:
      "Protect & Beautify Your Pavers in Lakewood Ranch, Sarasota & Bradenton",
    description:
      "Over time, Florida's harsh sun, rain, and humidity can cause brick pavers to fade, shift, and grow algae or mold. Our professional paver sealing service in Lakewood Ranch, Sarasota, and Bradenton helps restore the natural color of your pavers, lock in joint sand, and create a long-lasting barrier against the elements.",
    longDescription: `Brick and concrete pavers are a significant investment in your property's curb appeal and functionality. Without proper sealing, Florida's intense UV radiation causes colors to fade, joint sand washes away allowing pavers to shift, and porous surfaces absorb stains and harbor organic growth. Our professional paver sealing service addresses all of these issues in a single comprehensive treatment.

Our process begins with a thorough cleaning to remove all dirt, stains, and organic growth. We then re-sand joints with polymeric sand to stabilize the paver field and prevent weed growth. Finally, we apply a premium penetrating or film-forming sealer that enhances color, repels stains, and protects against UV fading. The result is a surface that looks better and stays cleaner longer.`,
    benefits: [
      "Restores and enhances natural paver color",
      "Locks in joint sand to prevent shifting and weed growth",
      "Creates a protective barrier against stains and UV fading",
      "Available in wet-look or natural finish sealers",
      "Extends paver lifespan and protects your investment",
    ],
    image: "/manus-storage/job-roof-after-2_67294a74.webp",
    metaTitle:
      "Paver Sealing Lakewood Ranch & Sarasota | Brick Paver Sealing | SRQ Wash",
    metaDescription:
      "Professional paver sealing in Lakewood Ranch, Sarasota, and Bradenton. Restore color, lock joint sand, and protect pavers from Florida's harsh climate. Free quotes.",
  },
];

export const SERVICE_AREAS = [
  {
    id: "lakewood-ranch",
    slug: "/service-area/lakewood-ranch",
    name: "Lakewood Ranch",
    state: "FL",
    description:
      "Serving all neighborhoods in Lakewood Ranch, FL with professional pressure washing, roof cleaning, house washing, and paver sealing.",
    metaTitle:
      "Pressure Washing Lakewood Ranch FL | SRQ Wash | Licensed & Insured",
    metaDescription:
      "Professional pressure washing in Lakewood Ranch, FL. House washing, roof cleaning, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated.",
  },
  {
    id: "sarasota",
    slug: "/service-area/sarasota",
    name: "Sarasota",
    state: "FL",
    description:
      "Serving Sarasota, FL with professional pressure washing, soft wash roof cleaning, exterior house washing, and commercial cleaning services.",
    metaTitle:
      "Pressure Washing Sarasota FL | SRQ Wash | Licensed & Insured",
    metaDescription:
      "Professional pressure washing in Sarasota, FL. House washing, roof cleaning, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated.",
  },
  {
    id: "venice",
    slug: "/service-area/venice",
    name: "Venice",
    state: "FL",
    description:
      "Serving Venice, FL with professional pressure washing, roof cleaning, house washing, and exterior cleaning services.",
    metaTitle:
      "Pressure Washing Venice FL | SRQ Wash | Licensed & Insured",
    metaDescription:
      "Professional pressure washing in Venice, FL. House washing, roof cleaning, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated.",
  },
  {
    id: "bradenton",
    slug: "/service-area/bradenton",
    name: "Bradenton",
    state: "FL",
    description:
      "Serving Bradenton, FL with professional pressure washing, soft wash roof cleaning, exterior house washing, and commercial cleaning services.",
    metaTitle:
      "Pressure Washing Bradenton FL | SRQ Wash | Licensed & Insured",
    metaDescription:
      "Professional pressure washing in Bradenton, FL. House washing, roof cleaning, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated.",
  },
];

// Neighborhood-level service area entries for individual SEO pages
export const NEIGHBORHOOD_AREAS = [
  {
    id: "amber-creek",
    slug: "/service-area/amber-creek",
    name: "Amber Creek",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Amber Creek Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Amber Creek, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Amber Creek is a beautiful gated community in Lakewood Ranch, FL, known for its well-maintained homes and lush landscaping. SRQ Wash provides professional pressure washing services to Amber Creek homeowners, helping them maintain their property's curb appeal and HOA compliance.",
    why: "Florida's humid climate means Amber Creek homes regularly battle algae, mold, and mildew on roofs, driveways, and exterior walls. Our soft wash and pressure washing services remove these contaminants safely and effectively, keeping your Amber Creek home looking its best.",
  },
  {
    id: "aurora",
    slug: "/service-area/aurora",
    name: "Aurora",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Aurora Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Aurora, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Aurora is one of Lakewood Ranch's newer master-planned neighborhoods, featuring modern homes with tile roofs, paver driveways, and pool enclosures. SRQ Wash is the trusted pressure washing company for Aurora residents.",
    why: "New construction homes in Aurora are not immune to Florida's organic growth. Algae and mildew establish quickly on tile roofs and stucco exteriors. Our professional cleaning services protect your investment and keep your Aurora home looking brand new.",
  },
  {
    id: "avalon-woods",
    slug: "/service-area/avalon-woods",
    name: "Avalon Woods",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Avalon Woods Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Avalon Woods, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Avalon Woods is a charming community in Lakewood Ranch offering single-family homes with beautiful landscaping and community amenities. SRQ Wash serves Avalon Woods homeowners with professional exterior cleaning services.",
    why: "Avalon Woods homes benefit from regular professional cleaning to combat Florida's relentless humidity and organic growth. Our team uses eco-friendly solutions that are safe for your landscaping and the surrounding environment.",
  },
  {
    id: "azario-esplanade",
    slug: "/service-area/azario-esplanade",
    name: "Azario – Esplanade",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Azario Esplanade Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Azario Esplanade, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Azario – Esplanade is a premier resort-style community in Lakewood Ranch featuring luxury homes, a championship golf course, and world-class amenities. SRQ Wash provides the premium exterior cleaning services that Azario – Esplanade homes deserve.",
    why: "Luxury homes in Azario – Esplanade require a higher standard of care. Our team is experienced with high-end tile roofs, travertine pavers, and delicate stucco finishes. We treat every property with the same care and precision we would our own.",
  },
  {
    id: "azario-townhomes",
    slug: "/service-area/azario-townhomes",
    name: "Azario – Townhomes",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Azario Townhomes Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Azario Townhomes, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Azario Townhomes offers low-maintenance living in the heart of Lakewood Ranch. SRQ Wash helps townhome owners maintain their exterior surfaces with professional pressure washing and soft wash services.",
    why: "Townhome communities in Azario benefit from coordinated cleaning services. We work efficiently to clean multiple units and can coordinate with HOA management for community-wide cleaning programs.",
  },
  {
    id: "calusa-country-club",
    slug: "/service-area/calusa-country-club",
    name: "Calusa Country Club",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Calusa Country Club Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Calusa Country Club, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Calusa Country Club is a prestigious golf community in Lakewood Ranch featuring custom homes and manicured grounds. SRQ Wash provides professional exterior cleaning services to Calusa Country Club homeowners who demand the best.",
    why: "Golf community homes in Calusa Country Club are subject to strict HOA standards. Our professional cleaning services ensure your home meets community standards while protecting your investment from Florida's harsh climate.",
  },
  {
    id: "cresswind",
    slug: "/service-area/cresswind",
    name: "Cresswind (55+)",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Cresswind Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Cresswind 55+ community, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Cresswind is an active adult 55+ community in Lakewood Ranch offering resort-style living with beautiful homes and amenities. SRQ Wash proudly serves Cresswind residents with reliable, professional exterior cleaning services.",
    why: "Cresswind residents trust SRQ Wash for hassle-free exterior cleaning. We handle everything from scheduling to cleanup, making it easy for homeowners to maintain their property without the stress of DIY cleaning.",
  },
  {
    id: "del-webb-catalina",
    slug: "/service-area/del-webb-catalina",
    name: "Del Webb Catalina",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Del Webb Catalina Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Del Webb Catalina, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Del Webb Catalina is a vibrant 55+ active adult community in Lakewood Ranch. SRQ Wash serves Del Webb Catalina homeowners with professional pressure washing and soft wash services tailored to the community's needs.",
    why: "Del Webb Catalina homes benefit from regular professional cleaning to maintain their appearance and protect against Florida's organic growth. Our team is familiar with the community and provides reliable, consistent service.",
  },
  {
    id: "lorraine-lakes",
    slug: "/service-area/lorraine-lakes",
    name: "Lorraine Lakes",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Lorraine Lakes Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Lorraine Lakes, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Lorraine Lakes is one of Lakewood Ranch's most sought-after communities, featuring stunning lakefront homes, resort-style amenities, and beautiful landscaping. SRQ Wash is the preferred pressure washing company for Lorraine Lakes homeowners.",
    why: "Lakefront properties in Lorraine Lakes face unique challenges from moisture and organic growth. Our professional soft wash and pressure washing services protect your home's exterior surfaces and keep your property looking pristine year-round.",
  },
  {
    id: "monarch-acres",
    slug: "/service-area/monarch-acres",
    name: "Monarch Acres",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Monarch Acres Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Monarch Acres, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Monarch Acres is a distinctive community in Lakewood Ranch featuring spacious homes on larger lots. SRQ Wash provides professional exterior cleaning services to Monarch Acres homeowners.",
    why: "Larger properties in Monarch Acres have more exterior surface area to maintain. Our efficient team and professional equipment handle large-scale cleaning projects quickly and thoroughly, delivering outstanding results every time.",
  },
  {
    id: "monterey",
    slug: "/service-area/monterey",
    name: "Monterey",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Monterey Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Monterey, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Monterey is a family-friendly community in Lakewood Ranch with beautiful homes and a strong sense of community. SRQ Wash serves Monterey residents with professional pressure washing services that enhance curb appeal and protect property values.",
    why: "Monterey homeowners trust SRQ Wash for reliable, professional exterior cleaning. Our team understands the importance of maintaining your home's appearance in a community where curb appeal matters.",
  },
  {
    id: "palm-grove",
    slug: "/service-area/palm-grove",
    name: "Palm Grove",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Palm Grove Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Palm Grove, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Palm Grove is a beautiful community in Lakewood Ranch featuring single-family homes surrounded by lush Florida landscaping. SRQ Wash provides professional exterior cleaning services to Palm Grove homeowners.",
    why: "The lush landscaping in Palm Grove creates ideal conditions for algae and mold growth on exterior surfaces. Our professional cleaning services remove these contaminants and help prevent their return, keeping your Palm Grove home looking its best.",
  },
  {
    id: "sapphire-point",
    slug: "/service-area/sapphire-point",
    name: "Sapphire Point",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Sapphire Point Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Sapphire Point, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Sapphire Point is a premier gated community in Lakewood Ranch featuring luxury single-family homes with stunning lake views. SRQ Wash provides professional pressure washing services to Sapphire Point homeowners.",
    why: "Sapphire Point's lakefront location means homes are exposed to additional moisture and organic growth. Our professional cleaning services protect your investment and maintain the community's high standards of appearance.",
  },
  {
    id: "solera",
    slug: "/service-area/solera",
    name: "Solera",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Solera Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Solera, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Solera is a vibrant community in Lakewood Ranch offering a range of home styles and a welcoming neighborhood atmosphere. SRQ Wash serves Solera residents with professional exterior cleaning services.",
    why: "Solera homeowners appreciate our reliable, professional service and the dramatic results we deliver. From tile roof cleaning to driveway restoration, we help Solera homes look their absolute best.",
  },
  {
    id: "star-farms",
    slug: "/service-area/star-farms",
    name: "Star Farms",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Star Farms Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Star Farms, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Star Farms is one of Lakewood Ranch's most exciting new communities, featuring resort-style amenities, a variety of home styles, and a vibrant community atmosphere. SRQ Wash is proud to serve Star Farms homeowners with professional exterior cleaning services.",
    why: "New construction in Star Farms means fresh surfaces that benefit from early protection. Regular professional cleaning prevents organic growth from establishing and keeps your new home looking pristine for years to come.",
  },
  {
    id: "sweetwater",
    slug: "/service-area/sweetwater",
    name: "Sweetwater",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Sweetwater Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Sweetwater, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Sweetwater is a charming community in Lakewood Ranch known for its beautiful homes and friendly neighborhood feel. SRQ Wash provides professional pressure washing services to Sweetwater homeowners.",
    why: "Sweetwater residents trust SRQ Wash for consistent, high-quality exterior cleaning. Our team delivers the same professional results on every visit, helping you maintain your home's value and curb appeal.",
  },
  {
    id: "the-isles",
    slug: "/service-area/the-isles",
    name: "The Isles at Lakewood Ranch",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing The Isles at Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in The Isles at Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "The Isles at Lakewood Ranch is a stunning waterfront community featuring luxury homes surrounded by beautiful lakes and nature preserves. SRQ Wash provides premium exterior cleaning services to The Isles homeowners.",
    why: "Waterfront properties at The Isles face unique challenges from moisture, salt air, and organic growth. Our professional cleaning services protect your luxury home's exterior and maintain the community's exceptional standards.",
  },
  {
    id: "waterbury-park",
    slug: "/service-area/waterbury-park",
    name: "Waterbury Park",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Waterbury Park Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Waterbury Park, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Waterbury Park is a welcoming community in Lakewood Ranch offering quality homes and a great location close to top-rated schools and amenities. SRQ Wash serves Waterbury Park homeowners with professional exterior cleaning.",
    why: "Waterbury Park homeowners rely on SRQ Wash to keep their homes looking great year-round. Our professional team delivers consistent, reliable service that protects your property and enhances its curb appeal.",
  },
  {
    id: "waterside-bungalow-walk",
    slug: "/service-area/waterside-bungalow-walk",
    name: "Waterside – Bungalow Walk",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Waterside Bungalow Walk Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Waterside Bungalow Walk, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Waterside Bungalow Walk is a unique cottage-style community within Lakewood Ranch's Waterside development, featuring charming bungalow homes and a vibrant community atmosphere. SRQ Wash provides professional exterior cleaning services to Bungalow Walk residents.",
    why: "Bungalow-style homes in Waterside benefit from regular soft wash cleaning to maintain their distinctive character. Our gentle yet effective cleaning methods preserve your home's unique architectural details.",
  },
  {
    id: "waterside-emerald-landing",
    slug: "/service-area/waterside-emerald-landing",
    name: "Waterside – Emerald Landing",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Waterside Emerald Landing Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Waterside Emerald Landing, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Waterside Emerald Landing is a premier community within Lakewood Ranch's Waterside development, featuring luxury homes with stunning water views. SRQ Wash provides professional exterior cleaning services to Emerald Landing homeowners.",
    why: "Waterfront homes in Emerald Landing require specialized care to combat the additional moisture and organic growth that comes with lakeside living. Our professional team has the experience and equipment to keep your home looking pristine.",
  },
  {
    id: "waterside-kingfisher-estates",
    slug: "/service-area/waterside-kingfisher-estates",
    name: "Waterside – Kingfisher Estates",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Waterside Kingfisher Estates Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Waterside Kingfisher Estates, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Waterside Kingfisher Estates is an exclusive enclave within Lakewood Ranch's Waterside development, featuring luxury estate homes on premium lots. SRQ Wash provides the premium exterior cleaning services that Kingfisher Estates homes deserve.",
    why: "Estate homes in Kingfisher Estates represent significant investments that require professional care. Our team is experienced with luxury properties and delivers the meticulous attention to detail that these homes demand.",
  },
  {
    id: "waterside-lakehouse-cove",
    slug: "/service-area/waterside-lakehouse-cove",
    name: "Waterside – Lakehouse Cove",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Waterside Lakehouse Cove Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Waterside Lakehouse Cove, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Waterside Lakehouse Cove is a beautiful community within Lakewood Ranch's Waterside development, featuring homes with stunning lake views and resort-style amenities. SRQ Wash serves Lakehouse Cove homeowners with professional exterior cleaning.",
    why: "Lakehouse Cove's waterfront setting creates ideal conditions for algae and organic growth on exterior surfaces. Our professional cleaning services remove these contaminants and protect your home from Florida's challenging climate.",
  },
  {
    id: "waterside-shellstone",
    slug: "/service-area/waterside-shellstone",
    name: "Waterside – Shellstone",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Waterside Shellstone Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Waterside Shellstone, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Waterside Shellstone is a distinctive community within Lakewood Ranch's Waterside development, featuring beautiful homes with unique architectural character. SRQ Wash provides professional exterior cleaning services to Shellstone residents.",
    why: "Shellstone homeowners appreciate our professional approach and the outstanding results we deliver. Our team takes the time to understand your property's specific needs and tailors our cleaning approach accordingly.",
  },
  {
    id: "waterside-the-alcove",
    slug: "/service-area/waterside-the-alcove",
    name: "Waterside – The Alcove",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Waterside The Alcove Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Waterside The Alcove, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Waterside The Alcove is an intimate community within Lakewood Ranch's Waterside development, offering a private, upscale living experience. SRQ Wash provides professional exterior cleaning services to The Alcove homeowners.",
    why: "The Alcove's exclusive character demands a professional cleaning service that matches its standards. SRQ Wash delivers premium results with the discretion and professionalism that upscale communities expect.",
  },
  {
    id: "waterside-wild-blue",
    slug: "/service-area/waterside-wild-blue",
    name: "Waterside – Wild Blue",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Waterside Wild Blue Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Waterside Wild Blue, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Waterside Wild Blue is a stunning lakefront community within Lakewood Ranch's Waterside development, featuring luxury homes with breathtaking water views. SRQ Wash provides professional exterior cleaning services to Wild Blue homeowners.",
    why: "Wild Blue's lakefront location means homes are exposed to additional moisture and organic growth. Our professional soft wash and pressure washing services protect your luxury home and maintain the community's exceptional standards.",
  },
  {
    id: "windward",
    slug: "/service-area/windward",
    name: "Windward",
    parent: "Lakewood Ranch",
    state: "FL",
    metaTitle: "Pressure Washing Windward Lakewood Ranch FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Windward, Lakewood Ranch FL. Roof cleaning, house washing, driveway cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Windward is a premier community in Lakewood Ranch featuring luxury homes with stunning lake and preserve views. SRQ Wash is the trusted pressure washing company for Windward homeowners who demand professional results.",
    why: "Windward's natural setting creates ideal conditions for organic growth on exterior surfaces. Our professional cleaning services remove algae, mold, and mildew while protecting your home's surfaces from damage.",
  },
  // Additional cities and suburbs
  {
    id: "north-sarasota",
    slug: "/service-area/north-sarasota",
    name: "North Sarasota",
    parent: "Sarasota",
    state: "FL",
    metaTitle: "Pressure Washing North Sarasota FL | SRQ Wash",
    metaDescription: "Professional pressure washing in North Sarasota, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "North Sarasota is a diverse and vibrant part of Sarasota County with a mix of residential neighborhoods and commercial properties. SRQ Wash provides professional exterior cleaning services throughout North Sarasota.",
    why: "North Sarasota properties benefit from regular professional cleaning to combat Florida's humidity and organic growth. Our team delivers consistent, high-quality results that protect your property and enhance its appearance.",
  },
  {
    id: "south-sarasota",
    slug: "/service-area/south-sarasota",
    name: "South Sarasota",
    parent: "Sarasota",
    state: "FL",
    metaTitle: "Pressure Washing South Sarasota FL | SRQ Wash",
    metaDescription: "Professional pressure washing in South Sarasota, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "South Sarasota is home to beautiful residential neighborhoods, waterfront properties, and a thriving community. SRQ Wash provides professional pressure washing services throughout South Sarasota.",
    why: "South Sarasota's coastal proximity means properties face constant challenges from salt air, humidity, and organic growth. Our professional cleaning services protect your investment and keep your property looking its best.",
  },
  {
    id: "siesta-key",
    slug: "/service-area/siesta-key",
    name: "Siesta Key",
    parent: "Sarasota",
    state: "FL",
    metaTitle: "Pressure Washing Siesta Key FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Siesta Key, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Siesta Key is one of Florida's most beautiful barrier islands, known for its world-famous white quartz sand beaches and stunning waterfront properties. SRQ Wash provides professional exterior cleaning services to Siesta Key homeowners and businesses.",
    why: "Siesta Key's coastal environment is particularly harsh on exterior surfaces. Salt air, high humidity, and intense UV radiation accelerate organic growth and surface degradation. Our professional cleaning services are essential for maintaining Siesta Key properties.",
  },
  {
    id: "palmer-ranch",
    slug: "/service-area/palmer-ranch",
    name: "Palmer Ranch",
    parent: "Sarasota",
    state: "FL",
    metaTitle: "Pressure Washing Palmer Ranch Sarasota FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Palmer Ranch, Sarasota FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Palmer Ranch is a master-planned community in Sarasota featuring beautiful homes, golf courses, and excellent amenities. SRQ Wash provides professional exterior cleaning services to Palmer Ranch homeowners.",
    why: "Palmer Ranch's well-maintained community standards make professional exterior cleaning essential. Our team delivers results that meet HOA requirements and keep your Palmer Ranch home looking its best.",
  },
  {
    id: "osprey",
    slug: "/service-area/osprey",
    name: "Osprey",
    parent: "Sarasota",
    state: "FL",
    metaTitle: "Pressure Washing Osprey FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Osprey, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Osprey is a charming community in Sarasota County known for its natural beauty, waterfront properties, and quiet residential neighborhoods. SRQ Wash provides professional pressure washing services throughout Osprey.",
    why: "Osprey's natural setting and proximity to water create ideal conditions for organic growth on exterior surfaces. Our professional cleaning services protect your Osprey property and maintain its natural beauty.",
  },
  {
    id: "nokomis",
    slug: "/service-area/nokomis",
    name: "Nokomis",
    parent: "Sarasota",
    state: "FL",
    metaTitle: "Pressure Washing Nokomis FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Nokomis, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Nokomis is a peaceful coastal community in Sarasota County with beautiful beaches, waterfront homes, and a relaxed Florida lifestyle. SRQ Wash provides professional exterior cleaning services to Nokomis homeowners.",
    why: "Nokomis properties face constant challenges from coastal humidity and organic growth. Our professional cleaning services remove algae, mold, and mildew from roofs, driveways, and exterior walls, protecting your investment.",
  },
  {
    id: "englewood",
    slug: "/service-area/englewood",
    name: "Englewood",
    parent: "Sarasota",
    state: "FL",
    metaTitle: "Pressure Washing Englewood FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Englewood, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Englewood is a beautiful coastal community in Sarasota County known for its beaches, boating, and relaxed Florida lifestyle. SRQ Wash provides professional pressure washing services to Englewood homeowners and businesses.",
    why: "Englewood's coastal location makes regular professional cleaning essential. Salt air and humidity accelerate organic growth on all exterior surfaces. Our professional team delivers the deep cleaning your Englewood property needs.",
  },
  {
    id: "north-port",
    slug: "/service-area/north-port",
    name: "North Port",
    parent: "Sarasota",
    state: "FL",
    metaTitle: "Pressure Washing North Port FL | SRQ Wash",
    metaDescription: "Professional pressure washing in North Port, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "North Port is one of Florida's fastest-growing cities, with thousands of new and established homes throughout Sarasota County. SRQ Wash provides professional exterior cleaning services to North Port homeowners.",
    why: "North Port's rapid growth means many homeowners are discovering the need for professional exterior cleaning for the first time. Our team educates clients on the importance of regular cleaning and delivers outstanding results every time.",
  },
  {
    id: "west-bradenton",
    slug: "/service-area/west-bradenton",
    name: "West Bradenton",
    parent: "Bradenton",
    state: "FL",
    metaTitle: "Pressure Washing West Bradenton FL | SRQ Wash",
    metaDescription: "Professional pressure washing in West Bradenton, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "West Bradenton is a residential area in Manatee County with a mix of established neighborhoods and newer developments. SRQ Wash provides professional exterior cleaning services throughout West Bradenton.",
    why: "West Bradenton homeowners trust SRQ Wash for reliable, professional exterior cleaning. Our team delivers consistent results that protect your property and enhance its curb appeal.",
  },
  {
    id: "east-bradenton",
    slug: "/service-area/east-bradenton",
    name: "East Bradenton",
    parent: "Bradenton",
    state: "FL",
    metaTitle: "Pressure Washing East Bradenton FL | SRQ Wash",
    metaDescription: "Professional pressure washing in East Bradenton, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "East Bradenton is a growing area in Manatee County with many newer residential communities and established neighborhoods. SRQ Wash provides professional pressure washing services throughout East Bradenton.",
    why: "East Bradenton's growing residential base means more homeowners discovering the benefits of professional exterior cleaning. Our team delivers the same high-quality results to every East Bradenton property we serve.",
  },
  {
    id: "anna-maria-island",
    slug: "/service-area/anna-maria-island",
    name: "Anna Maria Island",
    parent: "Bradenton",
    state: "FL",
    metaTitle: "Pressure Washing Anna Maria Island FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Anna Maria Island, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Anna Maria Island is a stunning barrier island off the coast of Bradenton, known for its pristine beaches, charming Old Florida character, and beautiful waterfront properties. SRQ Wash provides professional exterior cleaning services to Anna Maria Island homeowners.",
    why: "Anna Maria Island's extreme coastal environment is among the most challenging for exterior surfaces in Florida. Salt air, constant humidity, and intense sun accelerate deterioration. Regular professional cleaning is essential for protecting your island property.",
  },
  {
    id: "parrish",
    slug: "/service-area/parrish",
    name: "Parrish",
    parent: "Bradenton",
    state: "FL",
    metaTitle: "Pressure Washing Parrish FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Parrish, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Parrish is a rapidly growing community in Manatee County with many new residential developments and a strong sense of community. SRQ Wash provides professional exterior cleaning services to Parrish homeowners.",
    why: "New construction in Parrish means fresh surfaces that benefit from early professional care. Regular cleaning prevents organic growth from establishing and keeps your new Parrish home looking pristine.",
  },
  {
    id: "ellenton",
    slug: "/service-area/ellenton",
    name: "Ellenton",
    parent: "Bradenton",
    state: "FL",
    metaTitle: "Pressure Washing Ellenton FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Ellenton, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Ellenton is a community in Manatee County with a mix of residential neighborhoods and commercial properties. SRQ Wash provides professional pressure washing services throughout Ellenton.",
    why: "Ellenton homeowners and businesses trust SRQ Wash for professional, reliable exterior cleaning. Our team delivers outstanding results that protect your property and enhance its appearance.",
  },
  {
    id: "venice-island",
    slug: "/service-area/venice-island",
    name: "Venice Island",
    parent: "Venice",
    state: "FL",
    metaTitle: "Pressure Washing Venice Island FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Venice Island, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Venice Island is the historic heart of Venice, FL, featuring charming streets, beautiful homes, and a vibrant downtown. SRQ Wash provides professional exterior cleaning services to Venice Island homeowners and businesses.",
    why: "Venice Island's historic character and coastal location require specialized cleaning expertise. Our team is experienced with older homes and delicate surfaces, delivering thorough cleaning without damage.",
  },
  {
    id: "south-venice",
    slug: "/service-area/south-venice",
    name: "South Venice",
    parent: "Venice",
    state: "FL",
    metaTitle: "Pressure Washing South Venice FL | SRQ Wash",
    metaDescription: "Professional pressure washing in South Venice, FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "South Venice is a residential community in Sarasota County with a mix of established homes and newer developments. SRQ Wash provides professional pressure washing services throughout South Venice.",
    why: "South Venice homeowners rely on SRQ Wash for professional exterior cleaning that protects their investment and maintains their home's curb appeal in Florida's challenging climate.",
  },
  {
    id: "wellen-park",
    slug: "/service-area/wellen-park",
    name: "Wellen Park",
    parent: "Venice",
    state: "FL",
    metaTitle: "Pressure Washing Wellen Park Venice FL | SRQ Wash",
    metaDescription: "Professional pressure washing in Wellen Park, Venice FL. Roof cleaning, house washing, driveway cleaning, pool cage cleaning, and paver sealing. Licensed, insured, 5-star rated. Free quotes.",
    intro: "Wellen Park is one of the fastest-growing master-planned communities in Southwest Florida, featuring thousands of new homes, resort-style amenities, and a vibrant town center. SRQ Wash is proud to serve Wellen Park homeowners with professional exterior cleaning services.",
    why: "New construction in Wellen Park means fresh surfaces that benefit from early professional care. Our team helps Wellen Park homeowners establish a regular cleaning routine that protects their new home from Florida's organic growth.",
  },
];

export const NEIGHBORHOODS = [
  "Amber Creek",
  "Aurora",
  "Avalon Woods",
  "Azario – Esplanade",
  "Azario – Townhomes",
  "Calusa Country Club",
  "Cresswind (55+)",
  "Del Webb Catalina",
  "Lorraine Lakes",
  "Monarch Acres",
  "Monterey",
  "Palm Grove",
  "Sapphire Point",
  "Solera",
  "Star Farms",
  "Sweetwater",
  "The Isles at Lakewood Ranch",
  "Waterbury Park",
  "Waterside – Bungalow Walk",
  "Waterside – Emerald Landing",
  "Waterside – Kingfisher Estates",
  "Waterside – Lakehouse Cove",
  "Waterside – Shellstone",
  "Waterside – The Alcove",
  "Waterside – Wild Blue",
  "Windward",
];

export const TESTIMONIALS = [
  {
    name: "Jennifer M.",
    location: "Lakewood Ranch, FL",
    rating: 5,
    text: "SRQ Wash did an incredible job on our roof and driveway. The crew was professional, on time, and the results were amazing. Our home looks brand new. Highly recommend!",
    service: "Roof Cleaning & Driveway Cleaning",
  },
  {
    name: "Robert T.",
    location: "Sarasota, FL",
    rating: 5,
    text: "I've tried other pressure washing companies before but SRQ Wash is on another level. They took the time to explain what they were doing and why. The house looks fantastic.",
    service: "Exterior House Washing",
  },
  {
    name: "Sarah K.",
    location: "Lakewood Ranch, FL",
    rating: 5,
    text: "Our pool cage was covered in green algae and the screens were almost opaque. After SRQ Wash came through, it looks like a brand new enclosure. Worth every penny.",
    service: "Pool Cage & Lanai Cleaning",
  },
  {
    name: "Michael D.",
    location: "Venice, FL",
    rating: 5,
    text: "Had my pavers sealed and they look absolutely stunning. The color is so vibrant and they told me the seal will protect them for years. Great work and great price.",
    service: "Paver Sealing",
  },
  {
    name: "Linda H.",
    location: "Bradenton, FL",
    rating: 5,
    text: "Called on a Tuesday, they were here by Thursday. Fast, efficient, and professional. The driveway went from embarrassingly dirty to spotless. Will definitely use again.",
    service: "Driveway Cleaning",
  },
  {
    name: "Tom W.",
    location: "Lakewood Ranch, FL",
    rating: 5,
    text: "SRQ Wash has been cleaning our home for two years now. Consistent quality, always on time, and they treat our property with care. Best pressure washing company in the area.",
    service: "Exterior House Washing",
  },
];

export const FAQS = [
  {
    question: "What is the difference between pressure washing and soft washing?",
    answer:
      "Pressure washing uses high-pressure water (1,300–4,000 PSI) to mechanically remove dirt from hard surfaces like concrete and brick. Soft washing uses low pressure (150–300 PSI) combined with specialized biodegradable cleaning solutions to kill and remove organic growth like algae, mold, and mildew at the cellular level. Soft washing results last 2–4 times longer because it eliminates the root cause of contamination rather than just the surface appearance.",
  },
  {
    question: "How often should I have my property pressure washed?",
    answer:
      "In Florida's humid climate, most properties benefit from professional cleaning more frequently than in other regions. For house washing and roof cleaning, we recommend every 1–3 years depending on tree coverage and environmental conditions. Driveways and concrete typically need cleaning annually. Pool cages and lanais may need cleaning every 6–12 months due to constant exposure to humidity and organic growth.",
  },
  {
    question: "How often should I have my house pressure washed in Lakewood Ranch?",
    answer:
      "Due to Florida's humid climate, we recommend annual house washing for most properties in Lakewood Ranch. Properties with significant tree coverage, north-facing walls, or those near water may benefit from cleaning every 6–12 months. Annual cleaning prevents organic growth from becoming established and damaging your exterior surfaces.",
  },
  {
    question: "What surfaces can be pressure washed?",
    answer:
      "We can clean a wide range of surfaces including driveways, sidewalks, patios, pool decks, fences, home exteriors (stucco, siding, brick), roofs, pool cages, screen enclosures, and commercial buildings. We assess each surface and use the appropriate method — pressure washing for hard surfaces and soft washing for delicate surfaces — to ensure safe, effective cleaning.",
  },
  {
    question: "Will pressure washing damage my landscaping?",
    answer:
      "We take extensive precautions to protect your landscaping. Before cleaning, we pre-wet all plants and shrubs adjacent to the work area. We use plant-safe, biodegradable cleaning solutions, and we rinse all vegetation thoroughly after completing the work. In over a decade of service, we have never had a landscaping damage claim.",
  },
  {
    question: "Do I need to prepare my property before the pressure washing service?",
    answer:
      "We ask that you remove fragile items, potted plants, and outdoor furniture from the immediate work area. Please close all windows and doors, and let us know about any gate codes or access requirements. Our team handles everything else — we bring all equipment, water, and cleaning solutions needed for the job.",
  },
  {
    question: "Is soft washing safe for my roof?",
    answer:
      "Yes — soft washing is actually the manufacturer-recommended method for cleaning most roofs. High-pressure washing can crack tiles, damage shingles, and void your roof warranty. Our soft wash process uses low pressure (similar to a garden hose) combined with professional-grade cleaning solutions that kill algae, mold, and lichen without any physical damage to your roofing materials.",
  },
  {
    question: "How long does a typical pressure washing job take?",
    answer:
      "Job duration varies by scope. A standard house washing takes 2–4 hours. Driveway and concrete cleaning typically takes 1–2 hours. Roof cleaning takes 2–3 hours. Pool cage cleaning takes 2–4 hours. Full-property packages including multiple services may take a full day. We provide a time estimate with every quote.",
  },
  {
    question: "Are you licensed and insured?",
    answer:
      "Yes. SRQ Wash is fully licensed and carries comprehensive general liability insurance and workers' compensation coverage. We are happy to provide proof of insurance upon request. Hiring an uninsured contractor puts your property and finances at risk — always verify insurance before allowing anyone to work on your property.",
  },
  {
    question: "Do you offer free estimates?",
    answer:
      "Absolutely. We provide free, no-obligation quotes for all residential and commercial services. You can request a quote by calling us, filling out our online contact form, or sending us a message. We typically respond within a few hours and can often schedule an estimate the same or next day.",
  },
];
